version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb-tpo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: tpo_database
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - mongodb-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express-tpo
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - mongodb-network

  neo4j:
    image: neo4j:5
    container_name: neo4j-tpo
    restart: always
    environment:
      NEO4J_AUTH: neo4j/devpass123
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1g
    ports:
      - "7474:7474" # UI Browser
      - "7687:7687" # Bolt (drivers, Python)
    volumes:
      - neo4j_data:/data
    networks:
      - mongodb-network

  redis:
    image: redis:7
    container_name: redis-tpo
    restart: always
    command: ["redis-server", "--appendonly", "no"] # solo cach√© en dev
    ports:
      - "6379:6379"
    networks:
      - mongodb-network

volumes:
  mongodb_data:
  neo4j_data:

networks:
  mongodb-network:
    driver: bridge